import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, "src");
const slidesDir = path.join(srcDir, "slides");
const templatePath = path.join(srcDir, "template.html");
const outputPath = path.join(__dirname, "index.html");

const marker = "{{SLIDES}}";
const generatedBanner = "<!-- Generated by presentation/build-slides.mjs. Edit presentation/src/ instead. -->\n";
const markdownScriptEnd = "__SCRIPT_END__";

const template = await readFile(templatePath, "utf8");
const slideFiles = (await readdir(slidesDir))
  .filter((name) => [".html", ".md"].includes(path.extname(name)))
  .sort();

const slideSections = await Promise.all(
  slideFiles.map(async (name) => {
    const source = await readFile(path.join(slidesDir, name), "utf8");
    const extension = path.extname(name);

    if (extension === ".html") {
      return source;
    }

    return [
      "        <section",
      "          data-markdown",
      '          data-separator="^\\r?\\n---\\r?\\n$"',
      '          data-separator-vertical="^\\r?\\n--\\r?\\n$"',
      "        >",
      '          <script type="text/template">',
      source.replaceAll("</script>", markdownScriptEnd).trimEnd(),
      "          </script>",
      "        </section>"
    ].join("\n");
  })
);

if (!template.includes(marker)) {
  throw new Error(`Template is missing ${marker}`);
}

const output = generatedBanner + template.replace(marker, slideSections.join("\n\n"));
await writeFile(outputPath, output);

console.log(`Wrote ${path.relative(__dirname, outputPath)} from ${slideFiles.length} slide source files.`);
