import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, "src");
const slidesDir = path.join(srcDir, "slides");
const templatePath = path.join(srcDir, "template.html");
const outputPath = path.join(__dirname, "index.html");

const marker = "{{SLIDES}}";
const generatedBanner = "<!-- Generated by presentation/build-slides.mjs. Edit presentation/src/ instead. -->\n";
const markdownScriptEnd = "__SCRIPT_END__";
const defaultMarkdownSlideClass = "content-slide";

function ensureDefaultMarkdownSlideClass(source) {
  const parts = source.trimEnd().split(/(^(?:---|--)$)/m);

  return parts
    .map((part, index) => {
      if (index % 2 === 1) {
        return part;
      }

      const trimmedStart = part.trimStart();

      if (!trimmedStart || /^<!--\s*\.slide:/.test(trimmedStart)) {
        return part;
      }

      const leadingWhitespace = part.match(/^\s*/)?.[0] ?? "";

      return `${leadingWhitespace}<!-- .slide: class="${defaultMarkdownSlideClass}" -->\n\n${part.slice(leadingWhitespace.length)}`;
    })
    .join("");
}

const template = await readFile(templatePath, "utf8");
const slideFiles = (await readdir(slidesDir))
  .filter((name) => path.extname(name) === ".md")
  .sort();

const slideSections = await Promise.all(
  slideFiles.map(async (name) => {
    const source = await readFile(path.join(slidesDir, name), "utf8");
    const markdownSource = ensureDefaultMarkdownSlideClass(source).replaceAll("</script>", markdownScriptEnd);

    return [
      "        <section",
      "          data-markdown",
      '          data-separator="^\\r?\\n---\\r?\\n$"',
      '          data-separator-vertical="^\\r?\\n--\\r?\\n$"',
      "        >",
      '          <script type="text/template">',
      markdownSource,
      "          </script>",
      "        </section>"
    ].join("\n");
  })
);

if (!template.includes(marker)) {
  throw new Error(`Template is missing ${marker}`);
}

const output = generatedBanner + template.replace(marker, slideSections.join("\n\n"));
await writeFile(outputPath, output);

console.log(`Wrote ${path.relative(__dirname, outputPath)} from ${slideFiles.length} slide source files.`);
